import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { FiAlertCircle } from "react-icons/fi";
import { MdKeyboardArrowRight } from "react-icons/md";
import { FiHeart } from "react-icons/fi";
import PropertyCard from '@/components/propertyCard/PropertyCard';
import Property from '@/components/property/Property';
import ImgPopup from '@/components/imgPopup/ImgPopup';
import Img from "../../assets/img-popup.jpeg";
import ImgTwo from "../../assets/img-popup-two.jpeg";
import ImgThree from "../../assets/img-popup-three.jpeg";
import Tab from '@/components/tab/Tab'
import Chart from '@/components/chart/Chart'
import BarChart from '@/components/chart/Chart'
import Map from '@/components/map/Map'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [open, setOpen] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://api.mapbox.com/mapbox-gl-js/v2.8.1/mapbox-gl.css' rel='stylesheet' />
      </Head>

      <div className='mx-4  md:w-9/12 md:mx-auto'>

        <div className='grid gap-4 grid-cols-2'>
          <Image onClick={() => setOpen(!open)} src={Img} className="cursor-pointer h-full rounded-[1rem]" />
          <div>
            <Image src={ImgTwo} className="cursor-pointer md:h-64 rounded-[1rem]" />
            <br />
            <Image src={ImgThree} className="cursor-pointer md:h-64 rounded-[1rem]" />
          </div>

        </div>
        {
          open && <ImgPopup open={open} setOpen={setOpen} />

        }


        <div className='flex items-center justify-between'>
          <div>
            <div className='flex gap-2 mt-3 items-center'>
              <p className='font-bold text-[#333333] text-[1.5rem] md:text-[2.25rem]'>$429K</p>
              <p className='bg-[#5FC65F] font-bold text-[0.875rem] h-6 px-2 rounded-xl text-white'>For Sale</p>
            </div>
            <p><span className='font-bold'>
              2294 Roylen Cir</span> State College, PA 16801</p>
          </div>
          <div>
            <FiHeart className='text-[#959595] h-6 w-6 md:h-9 md:w-9 ' />
          </div>
        </div>
        <br />
        <hr />
        <div className='flex gap-3 md:gap-14  w-full justify-center py-4 items-center pr-4'>
          <p><span className='font-extrabold'>3</span><span className='pl-1 text-[12px]'>bd</span></p>
          <div className='h-6 w-[2px] bg-[#ececec]'></div>
          <p><span className='font-extrabold'>2</span><span className='pl-1 text-[12px]'>ba</span></p>
          <div className='h-6 w-[2px] bg-[#ececec]'></div>   <p><span className='font-extrabold'>1856</span><span className='pl-1 text-[12px]'>sqft</span></p>
          <div className='h-6 w-[2px] bg-[#ececec]'></div> <p className='text-[1rem]'>Townhome</p>
        </div>
        <hr />



        {/* <button className='mt-8 w-full text-center border-[1px] rounded-[0.375rem] font-medium text-[1.125rem] text-[#200955] leading-[1.75rem] hover:bg-slate-50 py-1 my-4'>Connnect with a local agent to learn about regulations</button> */}
        <br />
        <div className='flex gap-4'>

          <p className='text-[#2e2e2e] pt-2 pb-5'>View property on</p>
          <div className='flex gap-2'>
            <div className='bg-[red] border-[0.5px] border-black text-white h-10 font-bold text-[1.2rem] w-10 rounded-full  flex items-center justify-center'>R</div>
            <div className='bg-[purple] border-[0.5px] border-black text-white h-10 font-bold text-[1.2rem] w-10 rounded-full  flex items-center justify-center'>V</div>
          </div>
        </div>
        <br /> 
        <p className='font-bold text-[1.5rem] leading-[2rem] text-[#200955]'>Revenue Projection</p>
        <BarChart />
        <p className='text-center text-[#a9a9a9]'>Seasonalized based on a market RevPAN of $220</p>
        <br />
        <br />
        <div className='grid grid-cols-2 md:grid-cols-4 gap-2'>
          <div className='border-l-[4px] pl-3'>
            <div className='flex gap-1 items-center'>
              <p className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0]'>Revenue</p>
              <FiAlertCircle className='text-[#a0a0a0] -mt-1' />
            </div>
            <p className='text-[#200955]'><span className='font-bold text-[1.5rem] leading-[2rem]'>$4,806</span>/mo</p>
          </div>
          <div className='border-l-[4px] pl-3'>
            <div className='flex gap-1 items-center'>
              <p className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0]'>Cap Rate</p>
              <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
            </div>

            <p className='text-[#200955]'><span className='font-bold text-[1.5rem] leading-[2rem]'>11.5%</span></p>
          </div>
          <div className='border-l-[4px] pl-3'>
            <div className='flex gap-1 items-center'>
              <p className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0]'>Gross Yeild</p>
              <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
            </div>

            <p className='text-[#200955]'><span className='font-bold text-[1.5rem] leading-[2rem]'>10.5%</span></p>
          </div>
          <div className='border-l-[4px] ]  pl-3'>
            <div className='flex gap-1 items-center'>
              <p className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0]'>Cash on Cash</p>
              <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
            </div>


            <p className='text-[#200955]'><span className='font-bold text-[1.5rem] leading-[2rem]'>14.4%</span></p>
          </div>
        </div>


     <br /> <br />
     <br />  <div className='border-[1px] rounded-[5px] ' >
          <div className='flex px-4 py-4 justify-between'>
            <p className='font-bold text-[1.5rem] leading-[2rem] text-[#200955]'>Calculator</p>
            <button className='border-[1px] rounded-[5px] py-1 px-4'>Edit Preference</button>

          </div>
          <hr />
          <br />
          <div className='flex justify-evenly'>
            <div className='flex flex-col items-center'>
              <p className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0]'>Cape Rate</p>
              <p className='text-[#200955]'><span className='font-bold text-[1.1rem] leading-[2rem]'>12.1%</span></p>
            </div>
            <div className='flex flex-col items-center'>
              <p className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0]'>Gross Yeild</p>
              <p className='text-[#200955]'><span className='font-bold text-[1.1rem] leading-[2rem]'>16.7%</span></p>
            </div>
            <div className='flex flex-col items-center'>
              <p className='text-[1.125rem] leading-[1.75rem] text-[#a0a0a0]'>Revenue</p>
              <p className='text-[#200955]'><span className='font-bold text-[1.1rem] leading-[2rem]'>17.6%</span></p>
            </div>
          </div>
          <br />
          <hr />
          <div className='flex justify-between items-center px-4 py-2'>
            <p className='text-[#200955] font-bold text-[1.1rem] leading-[2rem]'>Total Investment</p>
            <div className='flex gap-0 text-[#232323] font-bold items-center'>
              <p>$530,298</p>
              <MdKeyboardArrowRight fontSize={20} />
            </div>
          </div>
          <hr />
          <div className='flex justify-between items-center px-4 py-2'>
            <p className='text-[#200955] font-bold text-[1.1rem] leading-[2rem]'>Financing</p>
            <div className='flex gap-0 text-[#232323] font-bold items-center'>
              <p>$527,977/mo</p>
              <MdKeyboardArrowRight fontSize={20} />
            </div>
          </div>          <hr />
          <div className='flex justify-between items-center px-4 py-2'>
            <p className='text-[#200955] font-bold text-[1.1rem] leading-[2rem]'>Revenue</p>
            <div className='flex gap-0 text-[#232323] font-bold items-center'>
              <p>$8,999/mo</p>
              <MdKeyboardArrowRight fontSize={20} />
            </div>
          </div>          <hr />
          <div className='flex justify-between items-center px-4 py-2'>
            <p className='text-[#200955] font-bold text-[1.1rem] leading-[2rem]'>Expenses</p>
            <div className='flex gap-0 text-[#232323] font-bold items-center'>
              <p>$5,398/mo</p>
              <MdKeyboardArrowRight fontSize={20} />
            </div>
          </div>          <hr />
          <br />   <div className='flex justify-between items-center px-4 py-2'>
            <div className='flex gap-1 items-center'>
              <p className='text-[#200955] font-bold text-[1.1rem] leading-[2rem]'>Upfront Equity</p>
              <FiAlertCircle className='text-[#a0a0a0] -mt-1' />     </div>
            <div className='flex gap-0 text-[#232323] font-bold items-center'>
              <p>$140,298</p>
              <MdKeyboardArrowRight fontSize={20} />
            </div>
          </div>

          <div className='flex justify-between items-center px-4 py-2'>
            <div className='flex gap-1 items-center'>
              <p className='text-[#200955] font-bold text-[1.1rem] leading-[2rem]'>Net Operating Income</p>
              <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
            </div>

            <div className='flex gap-0 text-[#232323] font-bold items-center'>
              <p>$5,308/yr</p>
              <MdKeyboardArrowRight fontSize={20} />
            </div>
          </div>
          <div className='flex justify-between items-center px-4 pt-2 pb-4'>

            <div className='flex gap-1 items-center'>
              <p className='text-[#200955] font-bold text-[1.1rem] leading-[2rem]'>Leveraged Net Cash Flow</p>
              <FiAlertCircle className='text-[#a0a0a0] -mt-1 cursor-pointer' />
            </div>

            <div className='flex gap-0 text-[#232323] font-bold items-center'>
              <p>$5,308/yr</p>
              <MdKeyboardArrowRight fontSize={20} />
            </div>
          </div>
        </div>
      <br />
      <br />
      <p className='font-bold text-[1.5rem] leading-[2rem] text-[#200955]'>Location</p>
      <br />
     
           <Map />
<br />
<br />
        <p className='font-bold text-[1.5rem] leading-[2rem] text-[#200955]'>Market Data</p>
        <p className='text-[#2e2e2e] pt-2 pb-5'>Performance of Airbnbs in the overall market for State College, PA 16803. Data displayed is not impacted by filters in this search.</p>
        <Tab />
        <button className=' w-full text-center border-[1px] rounded-[0.375rem] font-medium text-[1.125rem] text-[#200955] leading-[1.75rem] hover:bg-slate-50 py-1 my-4'>View more market data for State College</button>
        <p className='font-bold text-[1.5rem] leading-[2rem] text-[#200955] py-8'>Nearby Airbnbs</p>

        <div className='grid grid-cols-1 lg:grid-cols-4 gap-4'>
          <Property />
          <Property />
          <Property />
          <Property />
        </div>
        <br />

        <p className='font-bold text-[1.5rem] leading-[2rem] text-[#200955]'>For Sale in Centre County</p>
        <p className='text-[#2e2e2e] pt-2 pb-5'>Nearby properties for sale with positive cash-on-cash returns</p>

        <div className='grid grid-cols-1 lg:grid-cols-3 gap-4'>

          <PropertyCard />
          <PropertyCard />
          <PropertyCard />
        </div>
        <br /><br />
        <div className='bg-[#f8f7f7] rounded-[0.75rem] p-[1rem] md:p-[5rem]'>
          <p className='font-bold text-[1.5rem] leading-[2rem] text-center text-[#200955] pb-10 md:pb-24'>Nearby Airbnbs for sale</p>

          <p className='text-[1.125rem] leading-[1.75rem] cursor-pointer hover:underline'>Centre County Airbnbs For Sale</p>
          <p className='text-[1.125rem] leading-[1.75rem] cursor-pointer hover:underline'>State College Airbnbs For Sale</p>
          <p className='text-[1.125rem] leading-[1.75rem] cursor-pointer hover:underline'>Pennsylvania Airbnbs For Sale</p>
          <p className='text-[1.125rem] leading-[1.75rem] cursor-pointer hover:underline'>16803 Airbnbs For Sale</p>
        </div>
      </div>
    </>
  )
}
